# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_WAITER:      [ROLE_WAITER]
        ROLE_EDITOR:      [ROLE_EDITOR]
        ROLE_REVIWER:     [ROLE_REVIEWER]
        ROLE_CHIEF:       [ROLE_CHIEF, ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: user
                        roles: 'ROLE_USER'
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

        user_provider:
            entity:
                class: AppBundle:User
                property: username


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            anonymous: ~
            pattern: ^/admin
            provider: user_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: user_index
                always_use_default_target_path: true
                target_path_parameter: user_index

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admin/user/new, roles: ROLE_SUPER_ADMIN }